apiVersion: v1
kind: Endpoints
metadata:
  name: ollama
subsets:
- addresses:
  - ip: {{ .Values.ollama.host }}
  ports:
  - port: {{ .Values.ollama.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  ports:
  - port: {{ .Values.ollama.port }}
    targetPort: {{ .Values.ollama.port }}
