apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: {{ .Values.postgres.port }}
  selector:
    app: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-master
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.global.postgresPassword | quote }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
