replicaCount: 3
image:
  repository: eugenekallis/servertoolpython-frontend
  tag: ff7a7439
service:
  type: ClusterIP
  port: 3000
api_url: "/api"

ingress:
  enabled: true
  className: "nginx"
  host: "servertool.cluster.lan"
