replicaCount: 2
image:
  repository: eugenekallis/mission-control-frontend
  tag: latest
service:
  type: ClusterIP
  port: 80
api_url: "http://mission-control-backend:5056"

ingress:
  enabled: true
  className: "traefik"
  host: "mission-control.k3s.lan"
