replicaCount: 2
image:
  repository: eugenekallis/mission-control-backend
  tag: latest
service:
  type: ClusterIP
  port: 5056

postgres:
  host: "192.168.1.150"
  port: "5432"
  user: "mission_control"
  database: "mission_control_dev"
  existingSecret:
    name: "mission-control-postgres"
    key: "password"
