global:
  environment: "Production"
  image:
    tag: "04.12.21-56.adabe5ca"
replicaCount: 2
image:
  repository: eugenekallis/llm-pipelines
  tag: latest
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: "traefik"
  host: "llm-pipelines.k3s.lan"
env:
  WEBHOOK_URL: ""
  OLLAMA_HOST: "http://ollama.lan:11434/v1"
  NEWS_API_URL: "https://newsapi.org/v2/everything"
  MODEL: "qwen3.5:4b"
  existingSecret:
    name: "llm-pipelines-secrets"
    keys:
      openai-api-key: OPENAI_API_KEY
      news-api-key: NEWS_API_KEY
