apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
      annotations:
        rollout.network.extension.pyserv.com/restartedAt: {{ now | quote }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_API_URL
          value: {{ .Values.api_url | default "http://backend:8080" | quote }}
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: {{ .Values.global.environment | default "Production" | quote }}
        - name: NEXT_PUBLIC_DOCKER_TAG
          value: {{ .Values.global.image.tag | default .Values.image.tag | quote }}
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
