global:
  environment: "Development"
  image:
    tag: "dev-04.14.03-04.e702d553"
  ollamaHost: "http://192.168.1.203:11434"
  redisUrl: "redis://redis:6379/0"
frontend:
  ingress:
    host: "dev.servertool.k3s.lan"
backend:
  managedCategory: "special-dev"
  magnetBridgeUrl: "http://servertool-dev-magnet-bridge:8081"
  corsAllowedOrigins: "http://dev.servertool.k3s.lan"
  database:
    existingSecret:
      name: "servertool-postgres"
      key: "password"
    host: "192.168.1.150"
    port: "5432"
    username: "postgres"
    name: "servertool_dev"
arr-searcher:
  replicaCount: 1
magnet-bridge:
  enabled: true
  env:
    MANAGED_CATEGORY: "special-dev"
    DEBUG_SKIP_MOVE: "true"
agent:
  replicaCount: 2
