global:
  environment: "Development"
  image:
    tag: "dev-03.30.20-42.452c2f16"
  ollamaHost: "http://192.168.1.125:11434"
  databaseUrl: "postgresql://postgres:postgres@db:5432/postgres"
  redisUrl: "redis://redis:6379/0"
  postgresPassword: "postgres"
frontend:
  ingress:
    host: "dev.servertool.k3s.lan"
backend:
  managedCategory: "special-dev"
  magnetBridgeUrl: "http://servertool-dev-magnet-bridge:8081"
arr-searcher:
  replicaCount: 1
magnet-bridge:
  enabled: true
  env:
    MANAGED_CATEGORY: "special-dev"
    DEBUG_SKIP_MOVE: "true"
agent:
  replicaCount: 2
