global:
  environment: "Production"
  image:
    tag: "04.26.00-58.a1b63b7d"
  ollamaHost: "http://192.168.1.203:11434"
  redisUrl: "redis://192.168.1.151:6379/0"
  redisChannelPrefix: ""
frontend:
  replicaCount: 2
  ingress:
    host: "servertool.k3s.lan"
backend:
  replicaCount: 2
  ollamaHost: "http://192.168.1.203:11434"
  magnetBridgeUrl: "http://servertool-prod-magnet-bridge:8081"
  corsAllowedOrigins: "https://servertool.k3s.lan"
  database:
    existingSecret:
      name: "servertool-postgres"
      key: "password"
    host: "192.168.1.150"
    port: "5432"
    username: "postgres"
    name: "servertool_prod"
agent:
  replicaCount: 2
arr-searcher:
  replicaCount: 2
magnet-bridge:
  enabled: true
  env:
    MANAGED_CATEGORY: "special"
    DEBUG_SKIP_MOVE: "false"
