global:
  environment: "Production"
  image:
    tag: "03.30.23-26.b814e0e7"
  ollamaHost: "http://192.168.1.203:11434"
  databaseUrl: "postgresql://postgres:postgres@db:5432/postgres"
  redisUrl: "redis://redis:6379/0"
  postgresPassword: "postgres"
frontend:
  replicaCount: 2
  ingress:
    host: "servertool.k3s.lan"
backend:
  replicaCount: 2
  ollamaHost: "http://192.168.1.203:11434"
  magnetBridgeUrl: "http://servertool-prod-magnet-bridge:8081"
agent:
  replicaCount: 2
arr-searcher:
  replicaCount: 2
magnet-bridge:
  enabled: true
  env:
    MANAGED_CATEGORY: "special"
    DEBUG_SKIP_MOVE: "false"
