global:
  environment: "Development"
  image:
    tag: "dev-04.08.20-55."
frontend:
  ingress:
    host: "dev.mission-control.k3s.lan"
backend:
  postgres:
    host: "192.168.1.150"
    port: "5432"
    database: "mission_control_dev"
    existingSecret:
      name: "mission-control-postgres"
      key: "password"
