apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-agent
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-agent
      annotations:
        rollout.network.extension.pyserv.com/restartedAt: {{ now | quote }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}-agent
              topologyKey: kubernetes.io/hostname
      containers:
      - name: agent
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Values.image.tag }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: REDIS_URL
          value: {{ .Values.global.redisUrl | quote }}
        - name: REDIS_CHANNEL_PREFIX
          value: {{ .Values.global.redisChannelPrefix | quote }}
        - name: OLLAMA_HOST
          value: "{{ .Values.global.ollamaHost }}"
        - name: MEDIA_DIRECTORIES
          value: {{ .Values.mediaDirectories | quote }}
        volumeMounts:
        - mountPath: {{ .Values.containerMountPath }}
          name: host-mount
          mountPropagation: HostToContainer
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: host-mount
        hostPath:
          path: {{ .Values.hostMountPath }}
          type: DirectoryOrCreate
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
