apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-agent
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-agent
      annotations:
        rollout.network.extension.pyserv.com/restartedAt: {{ now | quote }}
    spec:
      containers:
      - name: agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        volumeMounts:
        - mountPath: {{ .Values.containerMountPath }}
          name: host-mount
          mountPropagation: HostToContainer
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: host-mount
        hostPath:
          path: {{ .Values.hostMountPath }}
          type: DirectoryOrCreate
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
