replicaCount: 3
image:
  repository: eugenekallis/servertoolpython-backend
  tag: ac75b5e6
service:
  type: ClusterIP
  port: 8080
ollamaHost: "http://localhost:11434"
magnetBridgeUrl: "http://RELEASE-NAME-magnet-bridge:8081"
managedCategory: "special"
corsAllowedOrigins: ""
