apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servertool-development-env
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EugeneKallis/kubernetes-cluster.git
    targetRevision: HEAD
    path: apps/servertool-python/development
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
