apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: {{ .Values.postgres.port }}
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: {{ .Values.postgres.port }}
